# Generated by Django 6.0.4 on 2026-06-16 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='guest_type',
            field=models.CharField(blank=True, choices=[('DINE_IN', 'Dine-in Only'), ('STAY_IN', 'Stay-in Only'), ('BOTH', 'Stay + Dine-in')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('RECEPTION', 'Reception'), ('KITCHEN', 'Kitchen'), ('WAITER', 'Waiter'), ('GUEST', 'Guest')], max_length=20),
        ),
    ]
