# Generated by Django 6.0.4 on 2026-07-01 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_guest_type_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('RECEPTION', 'Reception'), ('KITCHEN', 'Kitchen'), ('WAITER', 'Waiter'), ('GUEST', 'Guest'), ('JANITOR', 'Janitor')], max_length=20),
        ),
    ]
