# Generated by Django 6.0.4 on 2026-08-18 05:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_orderitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sync_id',
            field=models.CharField(blank=True, db_index=True, default=uuid.uuid4, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
