apiVersion: v1
kind: Secret
metadata:
  name: smarthotel-secrets
  labels:
    app: smarthotel
type: Opaque
data:
  # Value: smarthotel_password_992
  POSTGRES_PASSWORD: c21hcnRob3RlbF9wYXNzd29yZF85OTI=
  # Value: django-insecure-31tp%gcn%zrj19y&cd9hk7p@8kg&d231xj0m^5&mji_&8vz$ao
  SECRET_KEY: ZGphbmdvLWluc2VjdXJlLTMxdHAlZ2NuJXpyajE5eSZjZDloazdwQThrZyZkMjMxeGowbV41Jm1qaV8mOHZ6JGFv
